title:            andres
titlehilight:     masegosa
tagline:          Researchg Scientist
description:      Researchg Scientist
logo:             andresrm-circle.jpg
#Comment out url when working locally to resolve base urls correctly
url:  https://andresmasegosa.github.io



# Owner/author information
owner:
  name:           andres r. masegosa
#  avatar:         avatar.png
  bio:            "Spanish-Granada"
  email:          arma@cs.aau.dk
  twitter:        andresmasegosa
  github:         andresmasegosa
#  instagram:      ctrunsthis
#  dribbble:       coletownsend
#  disqus:         balzac
  # Plug in your disqus shortname!
  # For Google Authorship https://plus.google.com/authorship
google_plus:  #other
# Analytics and webmaster tools stuff goes here
google_analytics: 
google_verify: 
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify: 

# Links to include in top navigation
# For external links add external: true
links:
#  - title: About
#    url: /about
  - title: publications
    url: /publications
  - title: Talks
    url: /talks
#  - title: Projects
#    url: /projects
  - title: Software
    url: /software
  - title: Projects
    url: /industry
#  - title: Blog
#    url: /blog
  - title: Short-CV
    url: /bio

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Spain/Madrid
future:      true
highlighter: pygments
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6


plugins:
  - jekyll-responsive-image
  
responsive_image:
  template: _includes/imager-js.html
  default_quality: 90
  sizes:
    - width: 320
    - width: 480
    - width: 800

# syntax_highlighter_opts:
#   coderay:
#     line_numbers:
#     line_numbers_start: 1
#     tab_width: 4
#     bold_every: 10
#     css: class

# https://github.com/mojombo/jekyll/wiki/Permalinks -- was /:categories/:title
permalink:   /:title/

# katex:
#   path_to_js: "assets/js/katex.min.js"

#include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]

# gems: ['jekyll/minibundle']

maruku:
  use_tex:  true

# for clean vector diagrams
assets:
  assets:
    - "*.svg"
  sources:
    - _svg

# http://www.rubydoc.info/gems/jekyll-minify-html/1.1.0
#env: production

sass:
  sass_dir: assets/sass
  style: compressed
